# Generated by Django 3.0 on 2020-02-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Property')),
            ],
        ),
    ]
