# Generated by Django 3.0 on 2020-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200211_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor_map',
        ),
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=False),
        ),
    ]
