# Generated by Django 3.0 on 2020-02-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200215_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_map',
            field=models.TextField(blank=True, default=None),
        ),
    ]
