# Generated by Django 3.0 on 2020-02-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200216_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='blog'),
        ),
    ]
