# Generated by Django 3.0 on 2020-02-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200216_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='review')),
                ('content', models.TextField()),
                ('career', models.CharField(max_length=50)),
                ('star', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('our_quality', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('selected_review', models.ManyToManyField(to='home.Review')),
            ],
        ),
    ]
