# Generated by Django 3.0 on 2020-02-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200217_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avatar',
        ),
    ]
