# Generated by Django 3.0 on 2020-02-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_review_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
