# Generated by Django 3.0 on 2020-03-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_comment_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Property')),
            ],
        ),
    ]
